### ISSUE TITLE
Improvements to soft volume maximum

### ISSUE THREAD

**Issue by ianparkinson** [mjoblin/vibinui#272]
Assuming you're happy with the fix at #271, I'd like to improve the soft volume maximum - but first, I have some questions about how to handle some edge cases through the status screen.

I'd like to:

1. Have volume unlimited by default, instead of defaulting to 50%. I think this would be less surprising to a new user and better support cases where the volume is handled by the streamer. Additionally, on my CXNv2, a volume of 15 (out of 30) is *very* quiet and, if you have the power amp set to a sensible level, suddenly dropping the streamer's volume to 15 makes the output barely audible.
2. Change the soft max from being percentage based, to using the amplifier's native volume values.

I have a prototype for this which leaves the soft max volume unset by default, which means we don't need to know the amplifier's native max volume to have a default for this setting. This is rendered as a blank field in the settings page. This seems to work very well, as Mantine's `NumberInput` expects blank values.

It has a slight drawback that if the user changes their amplifier, the old soft max value may be unsuitable. If we stick with a percentage value, this sort of situation is simplified - we can default to 100% and percentage values will carry over reasonably well between amplifiers. Am I safe to assume this is a rare enough case that we needn't worry about it?

The settings page currently shows very noticeable warning messages when particular settings are unavailable. For example, when there's no amplifier at all, the soft volume field includes a bright red warning message `Currently has no effect (no amplifier registered with Vibin)`. We also now have the consider the case when there is an amplifier, but it doesn't support numeric volumes (e.g. a CXNv2 in cbus mode). I wondered why you chose this approach over either disabling the field, or hiding it altogether, in situations where it has no purpose?

**Comment by mjoblin** [comment]
Yep, #271 (and the associated `vibin` PR) looks good. I still need to run them locally, and confirm that the Hegel changes work fine. Once that's done I can merge them -- but let me know if you'd prefer I not merge yet.

And your two suggestions sound great.

> Am I safe to assume this is a rare enough case that we needn't worry about it?

Yes this is definitely a safe assumption. No need to worry about that at all.

> I wondered why you chose this approach over either disabling the field, or hiding it altogether, in situations where it has no purpose?

Definitely no good reason for the current approach, and it's certainly more aggressive than warranted. I like the idea of disabling those fields, so at least the user knows that they're an option if/when they get a supported amplifier in the future. Feel free to adjust that behavior to something that you think makes more sense!

**Comment by mjoblin** [comment]
Just a heads-up that I went ahead and merged the volume-as-integer PRs after successful testing.

**Comment by ianparkinson** [comment]
Thanks! I'll send you a PR for this shortly. I've opted to both disable the field, and show the existing warning.

And just to record this for posterity:

We found that the CXNv2, in pre-amp mode, has its own Volume Limit setting in the Webmin page. This is exposed via `smoip` so _could_ be shown and controlled in vibinui. However, in practice, this setting doesn't actually do anything (I can still set the volume above that limit via the app and the dial on the streamer).

Therefore I don't think vibinui should either respect or control this setting. If the user sets it via vibinui, and it has some obscure behaviour that I haven't found - it may be difficult for the user to rediscover the relevant setting.

**Comment by mjoblin** [comment]
Awesome!

And my own quick note for posterity: At some point the user settings probably belong in a different location in the UI (not the "Status" screen). At that time it would also be worth rethinking some of the overall approach taken to user settings (both UI patterns and storage implementation).

**Comment by ianparkinson** [comment]
Thanks for merging #275 - if you're happy with the feature as it stands, I don't plan to make any further improvements to this myself. I'll let you decide whether to close out this bug.

**Comment by mjoblin** [comment]
Yep, definitely happy with it as-is. Many thanks for another awesome improvement!
